// Code generated by protoc-gen-go.
// source: data_1.proto
// DO NOT EDIT!

/*
Package testdata is a generated protocol buffer package.

It is generated from these files:
	data_1.proto
	data_2.proto
	timestamp.proto

It has these top-level messages:
	TestData_1
*/
package testdata

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type TestData_1 struct {
	Data []*TestData_1_Data_1 `protobuf:"bytes,1,rep,name=data" json:"data,omitempty"`
}

func (m *TestData_1) Reset()         { *m = TestData_1{} }
func (m *TestData_1) String() string { return proto.CompactTextString(m) }
func (*TestData_1) ProtoMessage()    {}

func (m *TestData_1) GetData() []*TestData_1_Data_1 {
	if m != nil {
		return m.Data
	}
	return nil
}

type TestData_1_Data_1 struct {
	Radar int32      `protobuf:"varint,1,opt,name=radar" json:"radar,omitempty"`
	Dummy int32      `protobuf:"varint,2,opt,name=dummy" json:"dummy,omitempty"`
	Time  *Timestamp `protobuf:"bytes,3,opt,name=time" json:"time,omitempty"`
}

func (m *TestData_1_Data_1) Reset()         { *m = TestData_1_Data_1{} }
func (m *TestData_1_Data_1) String() string { return proto.CompactTextString(m) }
func (*TestData_1_Data_1) ProtoMessage()    {}

func (m *TestData_1_Data_1) GetTime() *Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}
