// Code generated by protoc-gen-go.
// source: data_2.proto
// DO NOT EDIT!

package testdata

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type TestData_2 struct {
	Data []*TestData_2_Data_2 `protobuf:"bytes,1,rep,name=data" json:"data,omitempty"`
}

func (m *TestData_2) Reset()         { *m = TestData_2{} }
func (m *TestData_2) String() string { return proto.CompactTextString(m) }
func (*TestData_2) ProtoMessage()    {}

func (m *TestData_2) GetData() []*TestData_2_Data_2 {
	if m != nil {
		return m.Data
	}
	return nil
}

type TestData_2_Data_2 struct {
	A    int32      `protobuf:"varint,1,opt,name=a" json:"a,omitempty"`
	B    int64      `protobuf:"varint,2,opt,name=b" json:"b,omitempty"`
	C    int32      `protobuf:"zigzag32,3,opt,name=c" json:"c,omitempty"`
	D    int64      `protobuf:"zigzag64,4,opt,name=d" json:"d,omitempty"`
	E    float32    `protobuf:"fixed32,5,opt,name=e" json:"e,omitempty"`
	F    float64    `protobuf:"fixed64,6,opt,name=f" json:"f,omitempty"`
	Time *Timestamp `protobuf:"bytes,7,opt,name=time" json:"time,omitempty"`
}

func (m *TestData_2_Data_2) Reset()         { *m = TestData_2_Data_2{} }
func (m *TestData_2_Data_2) String() string { return proto.CompactTextString(m) }
func (*TestData_2_Data_2) ProtoMessage()    {}

func (m *TestData_2_Data_2) GetTime() *Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}
